// Editing: typing, undo, auto-indent, save, remote changes (merge, conflict), find bar, sub-words.
const fs = require('fs')
const { run, openProject, open, assert, text, WS, OUT } = require('../common.cjs')
const file = WS + '/demo/notes.txt'

run(async ({ page }) => {
  await openProject(page)
  await open(page, 'notes.txt')
  await page.click('.pane.active .ed-content')
  await page.keyboard.press('Control+Home')
  await page.keyboard.press('End')
  await page.keyboard.type(' added')
  assert((await text(page)).startsWith('line one added\n'), 'typing at the end of a line')
  assert(await page.isVisible('.tab.dirty'), 'tab marked as changed')
  await page.keyboard.press('Control+z')
  assert((await text(page)).startsWith('line one\n'), 'undo groups the typing')
  await page.keyboard.press('Control+Shift+z')
  assert((await text(page)).startsWith('line one added\n'), 'redo')
  await page.keyboard.press('Enter')
  await page.keyboard.type('    indent{')
  await page.keyboard.press('Enter')
  await page.keyboard.type('x')
  const t = await text(page)
  assert(t.includes('    indent{\n        x'), 'auto-indent after {')
  await page.keyboard.press('Control+s')
  await page.waitForTimeout(400)
  assert(fs.readFileSync(file, 'utf8') === t, 'saved to disk')
  assert(!(await page.isVisible('.tab.dirty')), 'clean after saving')

  fs.writeFileSync(file, t.replace('line two', 'line TWO (ia)'))
  await page.waitForTimeout(700)
  assert((await text(page)).includes('line TWO (ia)'), 'remote version applied to a clean buffer')

  await page.keyboard.press('Control+Home')
  await page.keyboard.type('// ')
  fs.writeFileSync(file, fs.readFileSync(file, 'utf8').replace('line three', 'line three (ia)'))
  await page.waitForTimeout(700)
  const merged = await text(page)
  assert(merged.startsWith('// line one') && merged.includes('line three (ia)'), 'three-way merge')
  assert(await page.isVisible('.tab.dirty'), 'still changed after the merge')

  const disk = fs.readFileSync(file, 'utf8')
  await page.keyboard.press('Control+Home')
  await page.keyboard.press('End')
  await page.keyboard.type(' LOCAL')
  fs.writeFileSync(file, disk.replace('line one added', 'line one REMOTE'))
  await page.waitForTimeout(800)
  assert(await page.isVisible('.banner-conflict'), 'conflict banner')
  assert(await page.isVisible('.tab.conflict'), 'tab marked as in conflict')
  assert((await text(page)).includes('LOCAL'), 'local buffer kept')
  await page.keyboard.press('Control+Alt+r')
  await page.waitForSelector('.merge')
  await page.screenshot({ path: OUT + '/merge.png' })
  await page.click('.merge-row.conflict .merge-gutter button[title^="Accept both"]')
  await page.click('.modal-foot .btn.primary')
  await page.waitForTimeout(300)
  const res = await text(page)
  assert(res.includes('LOCAL') && res.includes('REMOTE') && !(await page.isVisible('.banner-conflict')), 'conflict resolved (both)')

  await page.click('.pane.active .ed-content')
  await page.keyboard.press('F3')
  await page.waitForSelector('.findbar')
  await page.keyboard.type('line')
  await page.waitForTimeout(200)
  assert(/^\d+ \/ \d+$/.test((await page.textContent('.find-count')).trim()), 'search counter')
  await page.click('.findbar .toggle:has-text(".*")')
  await page.fill('.find-input', 'li(ne')
  await page.waitForTimeout(150)
  assert(await page.isVisible('.find-error'), 'invalid regex reported')
  await page.fill('.find-input', 'zzz')
  await page.waitForTimeout(150)
  assert(await page.isDisabled('.findbar button[title^="Next"]'), 'navigation disabled without result')
  await page.keyboard.press('Escape')
  assert(!(await page.isVisible('.findbar')), 'Escape closes the bar')
  assert(await page.evaluate(() => document.activeElement?.classList.contains('ed-content')), 'the focus goes back to the editor')

  await page.keyboard.press('Control+End')
  await page.keyboard.type('\nXMLHttpRequest item2 foo_bar')
  await page.keyboard.press('Home')
  const pos = () => page.evaluate(() => getSelection().focusOffset)
  const p0 = await pos()
  const stops = []
  for (let i = 0; i < 8; i++) {
    await page.keyboard.press('Alt+ArrowRight')
    stops.push((await pos()) - p0)
  }
  assert(JSON.stringify(stops) === '[3,7,14,19,20,24,25,28]', 'sub-words to the right ' + JSON.stringify(stops))
  const back = []
  for (let i = 0; i < 8; i++) {
    await page.keyboard.press('Alt+ArrowLeft')
    back.push((await pos()) - p0)
  }
  assert(JSON.stringify(back) === '[25,24,21,19,15,7,3,0]', 'sub-words to the left ' + JSON.stringify(back))
  await page.keyboard.press('Alt+Shift+ArrowRight')
  assert((await page.evaluate(() => getSelection().toString())) === 'XML', 'Shift+Alt extends the selection')
})
