// Editing: typing, undo, auto-indent, save, remote changes (merge, conflict), find bar, sub-words.
const fs = require('fs')
const { run, openProject, open, assert, text, WS, OUT } = require('../common.cjs')
const file = WS + '/demo/notes.txt'

run(async ({ page }) => {
  await openProject(page)
  await open(page, 'notes.txt')
  await page.click('.pane.active .ed-content')
  await page.keyboard.press('Control+Home')
  await page.keyboard.press('End')
  await page.keyboard.type(' ajout')
  assert((await text(page)).startsWith('line one ajout\n'), 'saisie en fin de ligne')
  assert(await page.isVisible('.tab.dirty'), 'onglet marqué modifié')
  await page.keyboard.press('Control+z')
  assert((await text(page)).startsWith('line one\n'), 'undo regroupe la frappe')
  await page.keyboard.press('Control+Shift+z')
  assert((await text(page)).startsWith('line one ajout\n'), 'redo')
  await page.keyboard.press('Enter')
  await page.keyboard.type('    indent{')
  await page.keyboard.press('Enter')
  await page.keyboard.type('x')
  const t = await text(page)
  assert(t.includes('    indent{\n        x'), 'auto-indentation après {')
  await page.keyboard.press('Control+s')
  await page.waitForTimeout(400)
  assert(fs.readFileSync(file, 'utf8') === t, 'enregistré sur le disque')
  assert(!(await page.isVisible('.tab.dirty')), 'propre après enregistrement')

  fs.writeFileSync(file, t.replace('line two', 'line TWO (ia)'))
  await page.waitForTimeout(700)
  assert((await text(page)).includes('line TWO (ia)'), 'version distante appliquée sur un buffer propre')

  await page.keyboard.press('Control+Home')
  await page.keyboard.type('// ')
  fs.writeFileSync(file, fs.readFileSync(file, 'utf8').replace('line three', 'line three (ia)'))
  await page.waitForTimeout(700)
  const merged = await text(page)
  assert(merged.startsWith('// line one') && merged.includes('line three (ia)'), 'fusion à trois voies')
  assert(await page.isVisible('.tab.dirty'), 'toujours modifié après la fusion')

  const disk = fs.readFileSync(file, 'utf8')
  await page.keyboard.press('Control+Home')
  await page.keyboard.press('End')
  await page.keyboard.type(' LOCAL')
  fs.writeFileSync(file, disk.replace('line one ajout', 'line one REMOTE'))
  await page.waitForTimeout(800)
  assert(await page.isVisible('.banner-conflict'), 'bandeau de conflit')
  assert(await page.isVisible('.tab.conflict'), 'onglet marqué en conflit')
  assert((await text(page)).includes('LOCAL'), 'buffer local conservé')
  await page.keyboard.press('Control+Alt+r')
  await page.waitForSelector('.merge')
  await page.screenshot({ path: OUT + '/merge.png' })
  await page.click('.merge-row.conflict .merge-gutter button[title^="Accepter les deux"]')
  await page.click('.modal-foot .btn.primary')
  await page.waitForTimeout(300)
  const res = await text(page)
  assert(res.includes('LOCAL') && res.includes('REMOTE') && !(await page.isVisible('.banner-conflict')), 'conflit résolu (les deux)')

  await page.click('.pane.active .ed-content')
  await page.keyboard.press('F3')
  await page.waitForSelector('.findbar')
  await page.keyboard.type('line')
  await page.waitForTimeout(200)
  assert(/^\d+ \/ \d+$/.test((await page.textContent('.find-count')).trim()), 'compteur de recherche')
  await page.click('.findbar .toggle:has-text(".*")')
  await page.fill('.find-input', 'li(ne')
  await page.waitForTimeout(150)
  assert(await page.isVisible('.find-error'), 'regex invalide signalée')
  await page.fill('.find-input', 'zzz')
  await page.waitForTimeout(150)
  assert(await page.isDisabled('.findbar button[title^="Suivant"]'), 'navigation désactivée sans résultat')
  await page.keyboard.press('Escape')
  assert(!(await page.isVisible('.findbar')), 'Échap ferme la barre')
  assert(await page.evaluate(() => document.activeElement?.classList.contains('ed-content')), "le focus revient dans l'éditeur")

  await page.keyboard.press('Control+End')
  await page.keyboard.type('\nXMLHttpRequest item2 foo_bar')
  await page.keyboard.press('Home')
  const pos = () => page.evaluate(() => getSelection().focusOffset)
  const p0 = await pos()
  const stops = []
  for (let i = 0; i < 8; i++) {
    await page.keyboard.press('Alt+ArrowRight')
    stops.push((await pos()) - p0)
  }
  assert(JSON.stringify(stops) === '[3,7,14,19,20,24,25,28]', 'sous-mots vers la droite ' + JSON.stringify(stops))
  const back = []
  for (let i = 0; i < 8; i++) {
    await page.keyboard.press('Alt+ArrowLeft')
    back.push((await pos()) - p0)
  }
  assert(JSON.stringify(back) === '[25,24,21,19,15,7,3,0]', 'sous-mots vers la gauche ' + JSON.stringify(back))
  await page.keyboard.press('Alt+Shift+ArrowRight')
  assert((await page.evaluate(() => getSelection().toString())) === 'XML', 'Maj+Alt étend la sélection')
})
