// Navigation, splits, global search, terminal, palette, settings, SQLite explorer and console.
const { run, openProject, assert, OUT } = require('../common.cjs')
run(async ({ page }) => {
  await openProject(page)
  await page.waitForTimeout(400)

  // Go to file (fuzzy)
  await page.keyboard.press('Control+Shift+n')
  await page.waitForSelector('.pick-input')
  await page.keyboard.type('apph')
  await page.waitForTimeout(400)
  assert((await page.textContent('.pick-item.selected')).includes('app.php'), 'goto file fuzzy finds app.php')
  await page.keyboard.press('Enter')
  await page.waitForTimeout(500)
  assert((await page.textContent('.pane.active .tab.active')).includes('app.php'), 'app.php opened')

  // Split right: same buffer in two panes
  await page.keyboard.press('Control+Backslash')
  await page.waitForTimeout(400)
  assert((await page.$$('.pane')).length === 2, 'split creates a second pane')
  await page.click('.pane.active .ed-content')
  await page.keyboard.press('Control+End')
  await page.keyboard.type('// shared')
  await page.waitForTimeout(150)
  const texts = await page.$$eval('.pane .ed-content', (els) => els.map((e) => e.textContent))
  assert(texts.length === 2 && texts[0] === texts[1] && texts[0].includes('// shared'), 'both panes show the same buffer')
  await page.keyboard.press('Control+z')
  await page.screenshot({ path: OUT + '/s5-split.png' })

  // Global search
  await page.keyboard.press('Control+Shift+f')
  await page.waitForSelector('.search-panel input')
  await page.keyboard.type('Greeter')
  await page.waitForSelector('.search-hit', { timeout: 5000 })
  assert((await page.$$('.search-hit')).length >= 3, 'global search lists matches')
  await page.click('.search-hit >> nth=1')
  await page.waitForFunction(() => document.querySelector('.pane.active .tab.active')?.textContent.includes('main.go'), null, { timeout: 5000 }).catch(() => {})
  assert((await page.textContent('.pane.active .tab.active')).includes('main.go'), 'search hit opens the file')

  // Terminal
  await page.keyboard.press('Control+Shift+Backquote')
  await page.waitForSelector('.xterm', { timeout: 5000 })
  await page.waitForTimeout(800)
  await page.keyboard.type('echo pod-$((40+2))\n')
  await page.waitForTimeout(800)
  const term = await page.textContent('.xterm-rows')
  assert(term.includes('pod-42'), 'terminal runs commands')

  // Bottom tools: Console at the bottom of the left rail, Problems at the bottom of the right one
  const box = (sel) => page.$eval(sel, (e) => e.getBoundingClientRect().toJSON())
  assert(await page.isVisible('.rail-left [data-zone=bottomLeft] .rail-btn.active[title="Console"]'), 'Console in the bottom group of the left rail')
  assert(await page.isVisible('.rail-right [data-zone=bottomRight] .rail-btn[title="Problems"]'), 'Problems in the bottom group of the right rail')
  const [railL, strip, sideL] = [await box('.rail-left'), await box('.bottom'), await box('.zone-left')]
  assert(Math.abs(railL.bottom - (await page.evaluate(() => innerHeight))) < 2, 'the rails take the full height')
  assert(strip.left >= railL.right - 1 && sideL.bottom <= strip.top + 1, 'the strip spans under the side panels')
  assert((await box('[data-tool=console]')).width > strip.width - 2, 'Console alone takes the whole strip')
  await page.click('.rail-right .rail-btn[title="Problems"]')
  await page.waitForSelector('[data-tool=problems] .btab:has-text("Output")')
  const before = await box('[data-tool=console]')
  assert(Math.abs(before.width - strip.width / 2) < 10, 'Console and Problems share the strip: ' + before.width)
  const handle = await box('.bottom > .resizer-x')
  await page.mouse.move(handle.x + 2, handle.y + 40)
  await page.mouse.down()
  await page.mouse.move(handle.x + 122, handle.y + 40, { steps: 4 })
  await page.mouse.up()
  const after = await box('[data-tool=console]')
  assert(Math.abs(after.width - before.width - 120) < 6, 'the border between the two tools moves: ' + (after.width - before.width))
  assert((await box('[data-tool=problems]')).top === after.top, 'one height for the strip')
  await page.screenshot({ path: OUT + '/s5-bottom.png' })
  await page.click('.rail-right .rail-btn[title="Problems"]')
  assert(!(await page.isVisible('[data-tool=problems]')), 'Problems closed from its rail icon')

  // Icons dragged between the zones; the placement is kept by the session
  const group = (zone) => page.$$eval(`[data-zone=${zone}] .rail-btn`, (els) => els.map((e) => e.title))
  await page.click('.rail-right .rail-btn[title="Problems"]')
  await page.dragAndDrop('.rail-right .rail-btn[title="Problems"]', '[data-zone=left] .rail-btn[title="Search"]', { targetPosition: { x: 16, y: 3 } })
  assert(JSON.stringify(await group('left')) === JSON.stringify(['Explorer', 'Problems', 'Search', 'Git', 'Kanban']), 'Problems dropped before Search: ' + JSON.stringify(await group('left')))
  assert(await page.isVisible('.zone-left[data-tool=problems]'), 'a shown tool stays shown in its new zone')
  // An empty group only gets a height once the drag has started.
  await page.hover('[data-zone=bottomLeft] .rail-btn[title="Console"]')
  await page.mouse.down()
  await page.mouse.move(20, 300, { steps: 3 })
  await page.hover('[data-zone=bottomRight]')
  await page.mouse.up()
  assert((await group('bottomRight'))[0] === 'Console' && (await group('bottomLeft')).length === 0, 'Console moved to the empty bottom right zone')
  assert(await page.isVisible('.zone-bottomRight[data-tool=console] .xterm'), 'the console keeps its terminal')
  await page.waitForTimeout(600)
  await page.reload()
  await page.waitForSelector('.rail-left')
  assert(JSON.stringify(await group('left')) === JSON.stringify(['Explorer', 'Problems', 'Search', 'Git', 'Kanban']) && (await group('bottomRight'))[0] === 'Console', 'placement kept after a reload')
  await page.screenshot({ path: OUT + '/s5-moved.png' })
  await page.keyboard.press('Control+Shift+a')
  await page.waitForSelector('.pick-input')
  await page.keyboard.type('Reset the tool layout')
  await page.waitForTimeout(200)
  await page.keyboard.press('Enter')
  await page.waitForTimeout(200)
  assert((await group('bottomLeft'))[0] === 'Console' && (await group('bottomRight'))[0] === 'Problems' && (await group('left')).length === 4, 'default placement restored')

  // Palette
  await page.keyboard.press('Control+Shift+a')
  await page.waitForSelector('.pick-input')
  await page.keyboard.type('settings')
  await page.waitForTimeout(200)
  await page.keyboard.press('Enter')
  await page.waitForSelector('.settings')
  await page.click('.settings-nav button:has-text("Keyboard shortcuts")')
  await page.waitForTimeout(200)
  await page.screenshot({ path: OUT + '/s6-keys.png' })
  await page.selectOption('.settings-body select', 'azerty')
  await page.waitForTimeout(200)
  const undoRow = await page.textContent('.keys-table tr:has-text("Undo")')
  assert(undoRow.includes('Ctrl+Z'), 'AZERTY preset shows Ctrl+Z for undo (code KeyW): ' + undoRow.trim().slice(0, 40))
  await page.selectOption('.settings-body select', 'qwerty')
  await page.click('.settings-nav button:has-text("Syntax highlighting")')
  await page.waitForTimeout(300)
  await page.screenshot({ path: OUT + '/s7-syntax.png' })
  await page.waitForTimeout(800)
  await page.click('.settings-nav button:has-text("History")')
  await page.waitForTimeout(300)
  assert((await page.$$('.history-entry')).length >= 2, 'settings history lists snapshots')
  await page.keyboard.press('Escape')

  // Infos: properties, connections and extensions stacked in one tool
  assert(!(await page.isVisible('.rail-left .rail-btn[title="Connections"]')), 'no Connections panel on the left')
  assert(!(await page.isVisible('.rail-right .rail-btn[title="Extensions"]')), 'no Extensions tool')
  await page.click('.rail-right .rail-btn[title="Infos"]')
  await page.waitForSelector('[data-testid=info-extensions]')
  const sections = await page.$$eval('.info-section > h2', (els) => els.map((e) => e.textContent))
  assert(JSON.stringify(sections) === JSON.stringify(['Properties', 'Connections', 'Extensions · language servers']), 'Infos sections in order ' + JSON.stringify(sections))
  const props = await page.textContent('[data-testid=info-properties] .card')
  assert(props.includes('Name') && props.includes('Root') && props.includes('Pod') && !props.includes('Target'), 'a single Project card: ' + props)
  assert(await page.isVisible('[data-testid=info-connections] h3:has-text("Local SSH keys")'), 'Infos lists the local SSH keys')
  await page.screenshot({ path: OUT + '/s8-infos.png' })

  // Database explorer with SQLite
  await page.click('.rail-right .rail-btn[title="Database explorer"]')
  await page.waitForSelector('.db-tool')
  await page.click('.db-tool button[title="Add a connection"]')
  await page.click('.conn-new button:has-text("SQLite")')
  await page.fill('.conn-form input[placeholder="var/data.db"]', 'app.db')
  await page.click('.conn-form button:has-text("Test")')
  await page.waitForSelector('.test-result')
  assert((await page.textContent('.test-result')).includes('successful'), 'test connection')
  await page.click('.conn-form button:has-text("Save")')
  await page.waitForTimeout(400)
  await page.click('.modal-head .icon-btn')
  await page.click('.conn-row')
  await page.waitForSelector('.db-tool .tree-row:has-text("main")')
  await page.click('.db-tool .tree-row:has-text("main")')
  await page.waitForSelector('.db-tool .tree-row:has-text("users")')
  await page.click('.db-tool .tree-row:has-text("users")')
  await page.waitForTimeout(300)
  assert(await page.isVisible('.db-tool .tree-row:has-text("users_email")'), 'columns and indexes listed')
  await page.dblclick('.db-tool .tree-row:has-text("users") >> nth=0')
  await page.waitForSelector('.table-view .grid')
  await page.waitForTimeout(300)
  assert((await page.textContent('.table-view .toolbar')).includes('of 250'), 'table view paginated with total')
  await page.screenshot({ path: OUT + '/s8-table.png' })

  // SQL console, two statements -> chooser
  await page.click('.db-tool button[title^="Open a console"]')
  await page.waitForSelector('.sql-console .ed-content')
  await page.waitForTimeout(300)
  await page.click('.sql-console .ed-content')
  await page.keyboard.type("SELECT count(*) AS n FROM users;\nSELECT name FROM users WHERE id < 4;")
  await page.keyboard.press('Control+Enter')
  await page.waitForSelector('.pick-item')
  assert((await page.textContent('.pick-item.selected')).includes('WHERE id < 4'), 'chooser preselects the active statement')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Enter')
  await page.waitForSelector('.sql-result .grid')
  assert((await page.textContent('.sql-result .grid')).includes('250'), 'first statement result')
  // manual transaction
  await page.click('.sql-console label.check input')
  await page.click('.sql-console .ed-content')
  await page.keyboard.press('Control+End')
  await page.keyboard.type("\nDELETE FROM users WHERE id > 200;")
  await page.keyboard.press('Control+Enter')
  await page.waitForSelector('.pick-item')
  await page.keyboard.press('Enter')
  await page.waitForTimeout(400)
  assert(await page.isVisible('.sql-console .badge.warn'), 'transaction open after DELETE')
  await page.click('.sql-console button:has-text("Rollback")')
  await page.waitForTimeout(300)
  assert(!(await page.isVisible('.sql-console .badge.warn')), 'rollback closes the transaction')
  await page.screenshot({ path: OUT + '/s9-sql.png' })
})
