// Kanban: board, new ticket, ticket view (description, plan, goals, notes, files,
// attachments), workflow buttons, test feedback, side panel, sync with a second window.
const fs = require('fs')
const { run, openProject, assert, WS, OUT } = require('../common.cjs')

run(async ({ page, ctx }) => {
  page.on('dialog', (d) => d.accept())
  await openProject(page)
  await page.click('.rail-left .rail-btn[title="Kanban"]')
  await page.waitForSelector('[data-testid=kanban-panel]')
  await page.click('[data-testid=kanban-open-board]')
  await page.waitForSelector('[data-testid=kanban-board]')
  assert((await page.$$('.kb-col')).length === 5, 'cinq colonnes actives')

  // New ticket.
  await page.click('[data-testid=kanban-new]')
  await page.fill('[data-testid=kanban-title]', 'Export CSV des commandes')
  await page.fill('[data-testid=kanban-description]', 'Ajouter un **export** CSV.')
  await page.click('[data-testid=kanban-create]')
  await page.waitForSelector('[data-testid=ticket-view]')
  assert((await page.textContent('[data-testid=ticket-title]')).includes('Export CSV'), 'ticket ouvert dans un onglet')
  assert((await page.textContent('[data-testid=ticket-status]')).includes('Nouveau'), 'état Nouveau')
  assert(await page.isVisible('[data-testid=ticket-description] strong'), 'description en Markdown')
  assert(await page.isVisible('.pane.active .tab.active:has-text("#1")'), "titre de l'onglet")
  assert(fs.existsSync(WS + '/demo/.ide/kanban.db'), 'base kanban.db dans .ide')
  assert(fs.readFileSync(WS + '/demo/.ide/.gitignore', 'utf8').includes('kanban.db'), 'kanban.db ignoré par git')
  assert(await page.isDisabled('[data-testid=ticket-to-ready]'), 'pas de passage à développer sans plan')

  // Plan and goals.
  await page.click('[data-testid=ticket-plan-edit]')
  await page.fill('.tk-md-input', '1. Ajouter la route\n2. Écrire le CSV')
  await page.click('[data-testid=ticket-plan-save]')
  await page.waitForSelector('[data-testid=ticket-plan] ol li')
  for (const g of ['La route /export répond', 'Le CSV a un en-tête']) {
    await page.fill('[data-testid=ticket-goal-input]', g)
    await page.keyboard.press('Enter')
    await page.waitForSelector(`[data-testid=ticket-goal]:has-text("${g}")`)
  }
  assert((await page.$$('[data-testid=ticket-goal]')).length === 2, 'deux goals ajoutés')
  await page.click('[data-testid=ticket-goal] input[type=checkbox]')
  await page.waitForSelector('[data-testid=ticket-goal].done')
  assert(true, 'goal coché')

  // Note, linked file, attachment.
  await page.fill('[data-testid=ticket-note-input]', 'Penser au séparateur `;`')
  await page.click('[data-testid=ticket-note-add]')
  await page.waitForSelector('[data-testid=ticket-note]:has-text("séparateur")')
  assert(true, 'note ajoutée')
  await page.click('[data-testid=ticket-file-add]')
  await page.waitForSelector('.pick-input')
  await page.keyboard.type('main.go')
  await page.waitForFunction(() => document.querySelector('.pick-item.selected')?.textContent.includes('main.go'))
  await page.keyboard.press('Enter')
  await page.waitForSelector('.tk-side .tk-row:has-text("src/main.go")')
  assert(true, 'fichier lié')
  await page.setInputFiles('[data-testid=ticket-attach]', { name: 'capture.txt', mimeType: 'text/plain', buffer: Buffer.from('bonjour') })
  await page.waitForSelector('.tk-side .tk-row:has-text("capture.txt")')
  assert(true, 'pièce jointe ajoutée')

  // A second window follows the changes.
  const page2 = await ctx.newPage()
  await page2.goto(page.url())
  await page2.waitForSelector('[data-testid=ticket-view]')

  // Workflow.
  await page.click('[data-testid=ticket-to-ready]')
  await page.waitForSelector('[data-testid=ticket-status]:has-text("À développer")')
  await page2.waitForSelector('[data-testid=ticket-status]:has-text("À développer")', { timeout: 5000 })
  assert(true, "l'autre fenêtre suit le changement d'état")
  await page.click('[data-testid=ticket-start]')
  await page.waitForSelector('[data-testid=ticket-status]:has-text("En cours")')
  await page.click('[data-testid=ticket-to-review]')
  await page.waitForSelector('[data-testid=ticket-status]:has-text("À tester")')
  await page.fill('[data-testid=ticket-note-input]', 'Le fichier est vide')
  await page.click('[data-testid=ticket-feedback-add]')
  await page.waitForSelector('[data-testid=ticket-status]:has-text("Correction")')
  assert(await page.isVisible('[data-testid=ticket-goal]:has-text("Le fichier est vide") .badge'), 'le retour devient un goal')
  await page.click('[data-testid=ticket-to-review]')
  await page.waitForSelector('[data-testid=ticket-status]:has-text("À tester")')
  await page.click('[data-testid=ticket-close]')
  await page.waitForSelector('[data-testid=ticket-status]:has-text("Terminé")')
  assert(true, 'ticket fermé')
  await page.click('.tk-section-toggle:has-text("Historique")')
  const events = await page.$$eval('.tk-events li', (l) => l.length)
  assert(events >= 7, `historique des changements (${events})`)

  // Board and panel.
  await page.click('.pane.active .tab:has-text("Kanban")')
  await page.waitForSelector('[data-testid=kanban-board]')
  assert(!(await page.isVisible('[data-testid=ticket-card-1]')), 'ticket fermé masqué du tableau')
  await page.click('.kb-toolbar button:has-text("Terminés")')
  await page.waitForSelector('[data-testid=ticket-card-1]')
  assert(true, 'ticket fermé dans la colonne des terminés')
  await page.screenshot({ path: OUT + '/kanban-board.png' })
  await page.click('.rail-left .rail-btn[title="Kanban"]')
  await page.click('.rail-left .rail-btn[title="Kanban"]')
  await page.click('[data-testid=kanban-panel] button[title="Nouveau ticket"]')
  await page.fill('[data-testid=kanban-title]', 'Second ticket')
  await page.click('[data-testid=kanban-create]')
  await page.waitForSelector('[data-testid=kanban-panel] [data-testid=ticket-card-2]')
  assert(true, 'nouveau ticket depuis le panneau')
  await page.waitForSelector('[data-testid=ticket-view] [data-testid=ticket-title]:has-text("Second ticket")')
  await page.screenshot({ path: OUT + '/kanban-ticket.png' })
  await page2.close()
})
