// Kanban: board, new ticket, ticket view (description, plan, goals, notes, files,
// attachments), workflow buttons, test feedback, side panel, sync with a second window.
const fs = require('fs')
const { run, openProject, assert, WS, OUT } = require('../common.cjs')

run(async ({ page, ctx }) => {
  page.on('dialog', (d) => d.accept())
  await openProject(page)
  await page.click('.rail-left .rail-btn[title="Kanban"]')
  await page.waitForSelector('[data-testid=kanban-panel]')
  await page.click('[data-testid=kanban-open-board]')
  await page.waitForSelector('[data-testid=kanban-board]')
  assert((await page.$$('.kb-col')).length === 5, 'five active columns')

  // New ticket.
  await page.click('[data-testid=kanban-new]')
  await page.fill('[data-testid=kanban-title]', 'CSV export of the orders')
  await page.fill('[data-testid=kanban-description]', 'Add a CSV **export**.')
  await page.click('[data-testid=kanban-create]')
  await page.waitForSelector('[data-testid=ticket-view]')
  assert((await page.textContent('[data-testid=ticket-title]')).includes('CSV export'), 'ticket opened in a tab')
  assert((await page.textContent('[data-testid=ticket-status]')).includes('New'), 'status New')
  assert(await page.isVisible('[data-testid=ticket-description] strong'), 'description in Markdown')
  assert(await page.isVisible('.pane.active .tab.active:has-text("#1")'), 'title of the tab')
  assert(fs.existsSync(WS + '/demo/.ide/kanban.db'), 'kanban.db base in .ide')
  assert(fs.readFileSync(WS + '/demo/.ide/.gitignore', 'utf8').includes('kanban.db'), 'kanban.db ignored by git')
  assert(await page.isDisabled('[data-testid=ticket-to-ready]'), 'no move to Ready without a plan')

  // Plan and goals.
  await page.click('[data-testid=ticket-plan-edit]')
  await page.fill('.tk-md-input', '1. Add the route\n2. Write the CSV')
  await page.click('[data-testid=ticket-plan-save]')
  await page.waitForSelector('[data-testid=ticket-plan] ol li')
  for (const g of ['The /export route answers', 'The CSV has a header']) {
    await page.fill('[data-testid=ticket-goal-input]', g)
    await page.keyboard.press('Enter')
    await page.waitForSelector(`[data-testid=ticket-goal]:has-text("${g}")`)
  }
  assert((await page.$$('[data-testid=ticket-goal]')).length === 2, 'two goals added')
  await page.click('[data-testid=ticket-goal] input[type=checkbox]')
  await page.waitForSelector('[data-testid=ticket-goal].done')
  assert(true, 'goal checked')

  // Note, linked file, attachment.
  await page.fill('[data-testid=ticket-note-input]', 'Mind the `;` separator')
  await page.click('[data-testid=ticket-note-add]')
  await page.waitForSelector('[data-testid=ticket-note]:has-text("separator")')
  assert(true, 'note added')
  await page.click('[data-testid=ticket-file-add]')
  await page.waitForSelector('.pick-input')
  await page.keyboard.type('main.go')
  await page.waitForFunction(() => document.querySelector('.pick-item.selected')?.textContent.includes('main.go'))
  await page.keyboard.press('Enter')
  await page.waitForSelector('.tk-side .tk-row:has-text("src/main.go")')
  assert(true, 'file linked')
  await page.setInputFiles('[data-testid=ticket-attach]', { name: 'capture.txt', mimeType: 'text/plain', buffer: Buffer.from('bonjour') })
  await page.waitForSelector('.tk-side .tk-row:has-text("capture.txt")')
  assert(true, 'attachment added')

  // A second window follows the changes.
  const page2 = await ctx.newPage()
  await page2.goto(page.url())
  await page2.waitForSelector('[data-testid=ticket-view]')

  // Workflow.
  await page.click('[data-testid=ticket-to-ready]')
  await page.waitForSelector('[data-testid=ticket-status]:has-text("Ready")')
  await page2.waitForSelector('[data-testid=ticket-status]:has-text("Ready")', { timeout: 5000 })
  assert(true, 'the other window follows the status change')
  await page.click('[data-testid=ticket-start]')
  await page.waitForSelector('[data-testid=ticket-status]:has-text("In progress")')
  await page.click('[data-testid=ticket-to-review]')
  await page.waitForSelector('[data-testid=ticket-status]:has-text("To test")')
  await page.fill('[data-testid=ticket-note-input]', 'The file is empty')
  await page.click('[data-testid=ticket-feedback-add]')
  await page.waitForSelector('[data-testid=ticket-status]:has-text("Fix")')
  assert(await page.isVisible('[data-testid=ticket-goal]:has-text("The file is empty") .badge'), 'the feedback becomes a goal')
  await page.click('[data-testid=ticket-to-review]')
  await page.waitForSelector('[data-testid=ticket-status]:has-text("To test")')
  await page.click('[data-testid=ticket-close]')
  await page.waitForSelector('[data-testid=ticket-status]:has-text("Done")')
  assert(true, 'ticket closed')
  await page.click('.tk-section-toggle:has-text("History")')
  const events = await page.$$eval('.tk-events li', (l) => l.length)
  assert(events >= 7, `history of the changes (${events})`)

  // Board and panel.
  await page.click('.pane.active .tab:has-text("Kanban")')
  await page.waitForSelector('[data-testid=kanban-board]')
  assert(!(await page.isVisible('[data-testid=ticket-card-1]')), 'closed ticket hidden from the board')
  await page.click('.kb-toolbar button:has-text("Done and abandoned")')
  await page.waitForSelector('[data-testid=ticket-card-1]')
  assert(true, 'closed ticket in the done column')
  await page.screenshot({ path: OUT + '/kanban-board.png' })
  await page.click('.rail-left .rail-btn[title="Kanban"]')
  await page.click('.rail-left .rail-btn[title="Kanban"]')
  await page.click('[data-testid=kanban-panel] button[title="New ticket"]')
  await page.fill('[data-testid=kanban-title]', 'Second ticket')
  await page.click('[data-testid=kanban-create]')
  await page.waitForSelector('[data-testid=kanban-panel] [data-testid=ticket-card-2]')
  assert(true, 'new ticket from the panel')
  await page.waitForSelector('[data-testid=ticket-view] [data-testid=ticket-title]:has-text("Second ticket")')
  await page.screenshot({ path: OUT + '/kanban-ticket.png' })
  await page2.close()
})
